### PR TITLE
Fix issue with transition into "OFF" state clearing the rgb value

### LINKED ISSUE #73: Using "transition" to turn off a bulb sets rgb to {0,0,0}. Turning back on results in no light.
I'm trying to use `transition` to dim my lights until they're off. Each method I've tried has problems:

MQTT Payload | Result
------------- | -------------
`{ "state": "OFF", "transition": 5 }` | No dimming. Light just turns off after 5 seconds
`{ "brightness": 0, "transition": 5 }` | Dims nicely, but light state remains ON
`{ "state": "OFF", "brightness": 0, "transition": 5 }`| Dims nicely, light state correctly sets to OFF, **but rgb gets set to {0,0,0}**. This means that when I turn back on the light, no light is produced regardless of brightness

Expectation would be for the rgb color value to be retained after transitioning into `{ "state": "off", "brightness": 0 }`

### PR DESCRIPTION
**Pull request by donkawechico**
# DRAFT -- Do not merge

## Bugfix
Fixes #73 .

## Current Issues

Changing the code to decrease brightness down to 0 doesn't fix the issue -- it just creates the same issue in a different place as the brightness stays at 0 even when you turn the bulb back on.

Naive solution is to save the  brightness value before transitioning down to 0. Then when turning on the light again, use the saved value (if one exists).

Or, possibly, set the brightness value -- in state ONLY -- back to the previous value while keeping the bulb OFF. However, that might briefly flicker the bulb light (if you send `{ "state": "OFF", "brightness": 255 }` you can see this flickering)

### CODE REVIEW

**Comment by stelgenhof** [comment]
Looking at the code once more I recall that this was kind of a quick hack :( Not my proudest coding...

Storing any previous values is possible, but keep in mind that EEPROM size is limited. 
Also I am not sure if only setting back the brightness is desired. What about the RGB values?

**Comment by donkawechico** [comment]
> Storing any previous values is possible, but keep in mind that EEPROM size is limited.

I think it can all be done with a single uint8 global for previous brightness. There's probably a clever way to do this without globals, but I'm new to this syntax and don't have a good mental picture yet of the execution flow.

> Also I am not sure if only setting back the brightness is desired. What about the RGB values?

From my experimentation, everything about the bulb is saved and restored when you turn back on EXCEPT for whichever property was brought down to 0. That property just stays at 0.

So if the bulb was red at brightness 200, and you transition to "OFF" by stepping down the brightness, then color is still red when you turn back on. (But at the moment, the bug is that brightness stays at 0 so it won't actually light up)

**Comment by donkawechico** [comment]
@stelgenhof do you have any advice on how to debug this stuff? Is there any way to test code changes without actually uploading to a bulb?

**Comment by donkawechico** [comment]
@stelgenhof Can you help me understand why [this conditional](https://github.com/stelgenhof/AiLight/blob/6aa83adaa3ad3a970c931cb8aa458c878b01ea72/src/light.ino#L420) is a ">" rather than a "<"?

```
// Cross fade the RGBW channels every millisecond
if (currentTransTime - startTransTime > transitionTime) {  // <----- This is the line I'm confused about
  if (stepCount <= 1000) {
    // Do the transition
  } else {
    // Finish transition
  }
}
```

The conditional at the top seems like it's saying "Do the transition stuff _after_ the transition time has elapsed". So a transition of 5 seconds would end up waiting 5 seconds, _then_ doing a 5 second transition. But I don't think this is what the bulb actually does, so I'm quite confused.

**Comment by stelgenhof** [comment]
@donnie As for testing/debugging I usually use a ESP8266 board (e.g. NodeMCU) for testing the core things. I just add some breakpoints in the code to check if the behaviour is as I expect. Ideally this project should have tests, but I haven't really got around to dig into that.

For your question on the code: that is just the check whether the set transition time has passed or not (everything is done in milliseconds).

**Comment by donkawechico** [comment]
>  that is just the check whether the set transition time has passed or not (everything is done in milliseconds).

Yes, I understand all that 😉  My question was why is it using a ">"? Shouldn't it be a "<"?

Right now, this is what it's doing (pseudo-code):

```
If we've EXCEEDED the transition time {
  Perform the transition and stop when it's done
}
```

Shouldn't it be:

```
If we HAVEN'T exceeded transition time {
  Perform the transition and stop when it's done
}
```

**Comment by stelgenhof** [comment]
I think you're right :(

**Comment by donkawechico** [comment]
Ah okay. What's weird is that when I test transitions on my bulb, it feels like it starts _immediately_. So I wasn't sure I was interpreting the logic correctly.

I'll test it this evening and put up a separate PR if all looks good.

**Comment by donkawechico** [comment]
Ah. I _sorta_ see what's happening. But it's funky. This is hard to explain, so bear with me:

Turns out that "currentTransTime - startTransTime" is actually just measuring the number of milliseconds _between each tick of loopLight()_.

In AiLight, this is _always_ about 1-20 milliseconds and is entirely random based on performance. And then that value (in milliseconds) is getting compared to user-requested transitionTime (in _seconds_).

You'll notice that if you set a transition value of, say, 25 seconds, the light won't transition because it never takes longer than 25 milliseconds to complete an iteration of loopLight.

I assume this was unintentional. I'll see if I can do a little refactor tonight.

**Pull request closed without merging**
