### PR TITLE
Format repository as an Arduino library

### PR DESCRIPTION
**Pull request by per1234**
Since the repository is categorized under the `arduino` and `esp8266-arduino` topics on GitHub and uses the Arduino IDE's .ino file format, it only makes sense that it be compatible with the Arduino IDE. While there are a couple of possible approaches, I think formatting it as a library, with the sketches bundled as examples makes the most sense. After installing the library, the firmware will be accessible via the Arduino IDE's **File > Examples > AiLight** menu.

- Add `library.properties` Arduino IDE metadata file.
- Move firmware sketch files to `examples` folder.
- Move AiLight_Rainbow sketch to `examples` folder.
- Move library files to `src` folder.

I have left the firmware sketch named as it was originally: "main", but I think it would be more user friendly if it was given a more descriptive name. I'd be happy to update this PR if that's considered desirable.

I realize this PR represents a pretty significant change to the structure of the repository and would be happy to discuss other alternatives if this is not considered acceptable. I see no reason for this project to be unfriendly to Arduino IDE users. PlatformIO is 100% compatible with Arduino projects.

### CODE REVIEW

**Comment by stelgenhof** [comment]
Thank you for your PR!

I understand that the Github topics and .ino filename may indicate this is an Arduino project, however it is not intended to be. Could you explain what the benefits would be if this is formatted as an Arduino Library?

Cheers! Sacha

**Comment by per1234** [comment]
>Could you explain what the benefits would be if this is formatted as an Arduino Library?

#### Installation instructions for Arduino IDE with the current repository structure:

1. Download the latest **Source Code** from https://github.com/stelgenhof/AiLight/releases
2. Unzip the downloaded file.
3. Move the folder `lib/AiLight` to `{sketchbook folder}/libraries`. You can find the location of `{sketchbook folder}` in the Arduino IDE at **File > Preferences > Sketchbook location**
4. Rename the `src` folder to `main`
5. (In the Arduino IDE) File > Open > {unzipped folder}/main/main.ino > Open

#### Installation instructions with the proposed repository structure:

1. Download the latest **Source Code (zip)** from https://github.com/stelgenhof/AiLight/releases
2. (In the Arduino IDE) Sketch > Include Library > Add .ZIP Library > select the downloaded file > Open
3. File > Examples > AiLight > main

Using the current structure with the Arduino IDE requires some advanced understanding of how the Arduino IDE works (manual library installation, sketch folder must match sketch name). There are several opportunities to mess things up and have a bad user experience. The firmware sketches and library code are separated from each other, rather being kept bundled together, as the proposed structure allows.

My proposed repository structure is the standard for all Arduino libraries. Arduino users will likely already be familiar with the second installation procedure (or if not, they're going to need to learn it anyway). This structure is also required if you wanted to add the library to the [Arduino Library Manager](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ) index, which makes it even easier to install and update via the Arduino IDE.

**Comment by stelgenhof** [comment]
Perhaps my question was a bit misleading. I am very much familiar with the Arduino IDE and it's underlying structure. Actually I meant, what would be the benefits of using the Arduino IDE over PlatformIO?

In addition, your proposal essentially turns this into a (Arduino IDE) library. The AiLight firmware is not a library; it's an independent component serving only a single purpose (allowing to control a specific type of hardware).

**Comment by per1234** [comment]
>what would be the benefits of using the Arduino IDE over PlatformIO?

Hundreds of thousands, if not millions, of people are already using the Arduino IDE. I would much rather use the software I already have installed and am familiar with than install new software. I feel that the Arduino IDE is more beginner friendly. PlatformIO does allow for more advanced usage but not everyone is interested in that.

>The AiLight firmware is not a library

I'd say this component of the project:
https://github.com/stelgenhof/AiLight/tree/develop/lib/AiLight
is a library.

The library format is just a convenient package. When you have multiple sketches and a library that go together the easiest way to package them together is as a library with example sketches. It could also be packaged as a sketch but you have two different sketches (the primary firmware and AiLight_Rainbow.ino) that both share the AiLight library. So either you need to install the AiLight library separately or else bundle duplicates of that library with both sketches.

**Comment by stelgenhof** [comment]
To give you bit of background: I started using Arduino IDE for this project initially (before it became public) however decided to migrate to PlatformIO for various reasons (better IDE integration allowing for C/C++ code completion, intelligent Library Management, platform independent, CI integration, CLI, etc.)

- Having many .ino files is an example of that initial project: PlatformIO supports these files and - like the Arduino IDE - merges these into a temporary .cpp file. At the moment these files serve only as an easy way to organize the code. Other than that, there is no real reason to use the .ino Arduino extension.

- The 'AiLight_Rainbow.ino' file is actually an example that got astray in this repository and I will remove it.  

- The 'AiLight.hpp' and 'AiLight.cpp' files are just convenience classes for the firmware, and could indeed be used as a library. But these only serve an internal purpose.

It looks like the .ino files, the 'AiLight_Rainbow.ino' file and the Github topics may have caused confusion this is an Arduino project. My apologies for that.

I'd like to iterate that I have not designed this as an Arduino project / code. The choice for PlatformIO has served me well until now and have no plans to change that.

Cheers! Sacha

**Comment by bukurat** [comment]
@per1234  have a look at the Tasmota firmware. That  repository is set up for platformio and the Arduino IDE and doesn’t include creating a library for the Arduino IDE.

**Comment by per1234** [comment]
Sure, it's structured as an Arduino sketch. I already said that was another option and explained why I chose the library structure in my last reply. Now that you have said that AiLight_Rainbow.ino will be removed the situation is different.

The biggest issue with trying to use this project as a sketch as-is is that the sketch folder name (`src`) does not match any of the .ino file names. The Arduino IDE requires that a sketch be located in a folder of the same name. When opening a file that does not meet this sketch/folder name matching requirement the Arduino IDE presents a dialog:

The file "main.ino" needs to be inside a sketch folder named "main".
Create this folder, move the file, and continue?

After clicking "OK" the Arduino IDE currently moves only the file main.ino to the new folder, leaving behind the other source files. This causes compilation of the sketch to fail.

In the Tasmota repository the folder name is sonoff and the sketch file name is sonoff.ino.

The most minimal solution would be to add a file named src.ino, which could just be blank. I would prefer giving the sketch folder and sketch filename a descriptive name instead.

Needing to manually install the AiLight library is also not ideal. Since you have said that there is no intention for that library to be shared between multiple separate programs it would make sense to just bundle it with the sketch. This could be done by just moving the files to the sketch folder. If it was preferable to still keep the library files separate then they can be placed under the `src` subfolder of the sketch folder, and the `#include` directive in main.h changed accordingly:
```cpp
#include "src/AiLight.hpp"
```

**Comment by stelgenhof** [comment]
Thanks! I understand these would be the changes / steps needed to make it work in the Arduino IDE. 

Again, why do you think it is a good idea to have it work in the Arduino IDE (The fact that the Arduino IDE is used by perhaps millions of users is not a compelling reason for me)

I'm not trying to be difficult, just want to understand the rationale behind this request :)

Cheers! Sacha

**Comment by per1234** [comment]
Let me flip it around: Why do you think it is **not** a good idea for it to work in the Arduino IDE?

**Comment by stelgenhof** [comment]
I can definitely answer that (and believe I already have) but would like to hear yours first.

**Comment by per1234** [comment]
Standards are a good thing. Years before PlatformIO Arduino created a standard of how a sketch should be formatted. It's a logical standard. It makes sense for a multi-file sketch to have a primary .ino file and the Arduino IDE needs a way to know which .ino file is the primary one. Thus the requirement for the filename to match the folder name.

Then PlatformIO came along and allowed people to use the Arduino framework without following the standards established by the Arduino IDE. Now for no good reason we have new standards. PlatformIO works fine with the Arduino standard so this breakage is not necessary. I'm seeing more and more of these libraries and programs that use the Arduino framework, are advertised as "Arduino", yet are just slightly not compatible with the Arduino standard.

One of the primary reasons for the success of the Arduino project is the huge number of compatible sketches and libraries published by the community. This code has been available to everyone, regardless of which IDE they happen to prefer. Now I'm seeing this split caused by PlatformIO users. The work of community members like you are not contributed back to the Arduino project, yet you benefit tremendously from all the work done on the Arduino project over the years.

Of course I don't expect everything to be "Arduino". If someone doesn't want to use the arduino framework that's fine and quite understandable.

**Comment by stelgenhof** [comment]
Standards can be good, but sometimes there are other ways to achieve the same thing.

PlatformIO utilizes the same toolchain and framework as the Arduino IDE. As such, in my view PlatformIO is not a contender, only another, different way to develop and build your embedded project. It offers some benefits over the Arduino IDE that I feel are valuable and to date has served this project well.

‘It is what we know already that often prevents us from learning.’ – Claude Bernard

**Comment by per1234** [comment]
So your answer to my question boils down to: "Because I don't want it to work in the Arduino IDE".

**Comment by nickrout** [comment]
I have used both, and massively prefer platformio, accordingly I (a mere user) am happy for the project to stay as is.
If it is correct that "The Arduino IDE requires that a sketch be located in a folder of the same name." then that is just retarded.

**Comment by per1234** [comment]
This is the sort of snobby attitude I keep seeing from PlatformIO users. I've already explained why it's a reasonable requirement for the sketch filename to match the folder name.

I absolutely understand why someone would prefer to use PlatformIO over the Arduino IDE. I also understand why someone would prefer the Arduino IDE over PlatformIO. It's a good thing to have choices. That's why it's harmful for a project to intentionally exclude one of those choices. I would want my project to be easily accessible to the users of any IDE, as long as that could be easily accommodated.

**Comment by bukurat** [comment]
I don’t believe it’s a snobby attitude for Sacha to decide which platform he wants to use to create his software.  The Arduino IDE was created as a learning tool for artists and non programmers and deliberately hides details from the user, resulting in it having to do a lot of work behind the scenes to turn a sketch into source code that can be compiled by the toolchain without errors.
Having said that, its good at what it does but the limitations show when you are working with multiple source files and projects with more than a few hundred lines of source code.
If you want a version that can be dropped into an Arduino IDE and will compile without errors @per1234, why don’t you fork the project to your own GIT repository and rename the directories and files as you see fit.

**Comment by per1234** [comment]
>I don’t believe it’s a snobby attitude for Sacha to decide which platform he wants to use to create his software.

I don't either. My comment about "snobby attitude" was not directed at stelgenhof, it was in response to nickrout's comment.

Of course it's completely up to stelgenhof how this repository should be managed. I merely submitted a proposal, there's never an obligation to merge a pull request. stelgenhof engaged me in a discussion on this topic and, although we disagree, I think it has been quite civil other than the offensive comment from nickrout.

>The Arduino IDE was created as a learning tool for artists and non programmers and deliberately hides details from the user, resulting in it having to do a lot of work behind the scenes to turn a sketch into source code that can be compiled by the toolchain without errors.

PlatformIO exactly reproduces all that same "behind the scenes" work the Arduino IDE does. The only exception is that PlatformIO is not quite so good at dependency resolution as the Arduino IDE in certain cases. You can set some options in platformio.ini that will usually fix that. So this is absolutely not a valid argument against the Arduino IDE. Of course PlatformIO also gives you the option of working outside the arduino framework if you like, and I would never expect such a project to add support for the Arduino IDE.

>its good at what it does but the limitations show when you are working with multiple source files and projects with more than a few hundred lines of source code.

I regularly use the Arduino IDE with projects much more complex than that. Heck, look at the [Marlin firmware](https://github.com/MarlinFirmware/Marlin/tree/1.1.x/Marlin), which has something like 256 source files and works fine with the Arduino IDE. The main benefit I see the free version of PlatformIO offer over the Arduino IDE within the arduino framework is the ability to set build flags on a per-project basis. Arduino specifically has rejected this functionality because they are concerned it would lead to library authors providing interfaces that are not beginner friendly. I do think that's a reasonable point but I also miss this feature sometimes. Of course it's possible to customize build flags as you like in the Arduino IDE, but you can't associate specific flags with a project. There are some other cool features of the pay version of PlatformIO but my poor hobbyist budget can't cover that so they don't matter to me.

You can complain about the Arduino IDE's editor but you can use any editor you like with the Arduino IDE so I don't buy into that.

>why don’t you fork the project to your own GIT repository and rename the directories and files as you see fit.

That's exactly what I did with this PR. I did end up deleting my fork earlier today but it's all still available for anyone who wants it.

**Comment by nickrout** [comment]
I can't see anything offensive about me stating an opinion that I am happy with platformio and that this project should stay as is.

If you want offensive, I can do that. In the meantime, no one has been rude to you.

**Comment by stelgenhof** [comment]
@per1234 Were you able to successfully compile the firmware within Arduino IDE and PlatformIO with your PR? Want to give it a try, however your branch seems not to be available anymore?

**Comment by per1234** [comment]
>Were you able to successfully compile the firmware within Arduino IDE and PlatformIO with your PR

@stelgenhof yes I was able to compile with both.

>your branch seems not to be available anymore

I did end up deleting that branch yesterday but it's still in the Git history here:
https://github.com/stelgenhof/AiLight/tree/9fa2042e625a358d76324779022da0c73afffbb5

That's the project in library form but, with your intention to remove AiLight_Rainbow.ino revealed, I now think it is more suitable for sketch form. So here is a branch with the project in sketch form:
https://github.com/per1234/AiLight/tree/master

Here is Travis CI build of the sketch using both PlatformIO and Arduino IDE 1.8.5:
https://travis-ci.org/per1234/AiLight/builds/383575465

**Comment by stelgenhof** [comment]
Thanks for sharing your results. 

Yesterday I managed to get the firmware compiled using Arduino IDE using the library 'way', but not without a hassle :)

Did you compile it also using the Arduino IDE, meaning without Travis?

Using the Arduino IDE requires users to install dependent libraries manually. Some can be installed via the built-in Library Manager, some have to be installed by hand into the Arduino Library folder (AsyncMqttClient, my9291, ESPAsyncTCP and ESP Async WebServer).

This is an example I prefer PlatformIO over the Arduino IDE as in the PlatformIO configuration I can (on a project level) define the required libraries. In addition I can even indicate which version of a library I want to use if need to be.

**Comment by per1234** [comment]
>Did you compile it also using the Arduino IDE, meaning without Travis?

Of course. I just did the Travis CI build as a way to provide an online demonstration of the sketch compiling.

>Using the Arduino IDE requires users to install dependent libraries manually. Some can be installed via the built-in Library Manager, some have to be installed by hand into the Arduino Library folder (AsyncMqttClient, my9291, ESPAsyncTCP and ESP Async WebServer).

It's not necessary to do a true manual installation of any of the libraries. For the ones not in the Library Manager index you only need to download the .zip file of the repository from GitHub and then do **Sketch > Include Library > Add .ZIP Library**. It's just par for the course for an Arduino IDE user so I don't really notice it. It is annoying when a project doesn't have any documentation of the dependencies and you need to go searching for the libraries (sometimes there are multiple candidates with the same name). In this case it was not too bad because I could just look up the dependencies listed in platformio.example.ini in the PlatformIO library index, which has links to the repositories.

>This is an example I prefer PlatformIO over the Arduino IDE as in the PlatformIO configuration I can (on a project level) define the required libraries. In addition I can even indicate which version of a library I want to use if need to be.

True, that is a very nice feature. But keep in mind that only works if the library has been added to the PlatformIO library manager. In the Arduino IDE you can add a library manager link in a comment of the sketch that the user can click to install the library. You can also use the Arduino IDE CLI to install a specific version or the latest release of libraries in the Library Manager index so the whole process can be scripted.

**Comment by stelgenhof** [comment]
The Arduino IDE is a good IDE and for sure - with some changes - this project can be made to work with it.

At the moment the priorities for this project are in other areas, and as such prefer to leave this project as is. Should many community members feel integration with the Arduino IDE is a missing critical piece, then I will definitely do that.

In the mean time, I am happy to forward people to your fork, in case they like to compile the AiLight firmware with the Arduino IDE.

Cheers! Sacha

**Pull request closed without merging**
